/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R */

#ifndef _Included_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
#define _Included_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    getSrv
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_getSrv
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    getfirma1
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_getfirma1
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    getdwdir
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_getdwdir
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    getdwcdir
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_getdwcdir
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    password
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_password
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    getdir
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_getdir
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    getSrvhd
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_getSrvhd
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    getcasses
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_getcasses
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    getweb
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_getweb
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    nn
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_nn
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    nnv
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_nnv
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    nna
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_nna
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    man
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_man
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    strenc
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_strenc
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    strdes
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_strdes
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    strtest
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_strtest
  (JNIEnv *, jclass);

/*
 * Class:     com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R
 * Method:    cs
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mreoz_mistypatcher2_Adaptadores_MRZH4CK3R_cs
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
